version: '3.6'
services:
  postgres-srv:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: development_pass
      POSTGRES_DB: postgres
    ports:
      - '5558:5432'
volumes:
  serverless_api_data: {}
